import Link from "next/link";
import { getCurrentProfile } from "@/lib/auth/profile";
import { requirePartnerOrganizationAccess,isUuidReference } from "@/lib/auth/authorization";
import { getDb } from "@/lib/db";
import { privacySchemaReady } from "@/lib/privacy/access";
import { PRIVACY_POLICY_VERSION,DEPLOYMENT_MODES } from "@/lib/privacy/policy";
import { submitSchoolAgreement,reviewSchoolAgreement,reviewPrivacyRightsRequest } from "./actions";
import { verifyRepresentative,revokeRepresentative } from "@/app/workspace/privacy/actions";
import { DataCaptureNotice } from "@/app/privacy/PrivacyNotice";
export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<{organizationId?:string}>}){
 const profile=await getCurrentProfile();if(!profile||profile.status!=='active')return <main><Link href="/auth/sign-in">Sign in / Đăng nhập</Link></main>;
 const {organizationId}=await searchParams;
 if(!isUuidReference(organizationId))return <main className="workspacePage"><div className="workspaceContent"><h1>Institution privacy governance / Quản trị quyền riêng tư</h1><form><label>Institution ID / Mã cơ sở<input name="organizationId" required/></label><button className="button">Open / Mở</button></form></div></main>;
 await requirePartnerOrganizationAccess(organizationId);
 if(!await privacySchemaReady())return <main className="workspacePage"><div className="workspaceContent"><h1>School privacy workflow is being prepared / Đang chuẩn bị quy trình quyền riêng tư</h1><DataCaptureNotice/><p>Optional processing stays blocked. / Xử lý tùy chọn vẫn chặn.</p></div></main>;
 const sql=getDb();const [agreements,authorities,rights]=await Promise.all([
  sql`select status,deployment_mode,policy_version from school_processing_agreements where organization_id=${organizationId}`,
  sql`select id,learner_id,representative_profile_id,status from learner_representative_authorities where organization_id=${organizationId}`,
  sql`select id,request_type,status,created_at from privacy_rights_requests where organization_id=${organizationId} order by created_at desc limit 50`,
 ]);
 return <main className="workspacePage"><div className="workspaceContent"><h1>School processing and family authority / Xử lý trường và thẩm quyền gia đình</h1><DataCaptureNotice/><p>Current agreement / Hợp đồng hiện tại: {agreements[0]?`${agreements[0].status} / ${agreements[0].deployment_mode}`:'not approved / chưa duyệt'}</p>
 <section className="panel"><h2>Submit processing agreement / Gửi hợp đồng xử lý</h2><p>Actual locations/providers are required. Requests for private/hybrid/local deployment do not move cloud records; only managed cloud can currently be approved. / Cần vị trí/nhà cung cấp thực. Yêu cầu private/hybrid/local không di chuyển hồ sơ; hiện chỉ managed cloud được duyệt.</p><form action={submitSchoolAgreement}><input type="hidden" name="organizationId" value={organizationId}/><input type="hidden" name="policyVersion" value={PRIVACY_POLICY_VERSION}/><label>Deployment / Triển khai<select name="deploymentMode">{DEPLOYMENT_MODES.map(m=><option key={m} value={m}>{({vitech_managed_cloud:'ViTech managed cloud / Cloud do ViTech quản lý',hybrid_institution:'Hybrid institution — request / Yêu cầu hybrid',capsule_private:'Intelligence Capsule / private — request / Yêu cầu private',institution_hosted_future:'Institution hosted — future request / Yêu cầu tự vận hành tương lai'})[m]}</option>)}</select></label>{[['schoolLegalName','Institution legal name / Tên pháp lý cơ sở'],['schoolContact','School privacy contact / Đầu mối trường'],['vitechContact','Registered ViTech operator/contact / Đơn vị/đầu mối ViTech'],['processingCountries','Actual countries: Auth, DB, host, AI, backups / Nước thực'],['approvedProviders','Approved providers and purposes / Nhà cung cấp và mục đích'],['retentionSchedule','Retention / Lịch lưu'],['agreementReference','Signed processing agreement reference / Tham chiếu hợp đồng'],['privacyReviewReference','Privacy review reference / Tham chiếu rà soát']].map(([key,label])=><label key={key}>{label}<textarea name={key} required minLength={5} maxLength={1500}/></label>)}<label>Cross-border review reference if applicable / Tham chiếu chuyển dữ liệu<textarea name="crossBorderReference" maxLength={500}/></label><label><input type="checkbox" name="authorized" required/> Authorised signatory; full notice read / Người ký được ủy quyền; đã đọc thông báo.</label><button className="button primary">Submit / Gửi</button></form>
 {profile.account_type==='platform_admin'&&<form action={reviewSchoolAgreement}><input type="hidden" name="organizationId" value={organizationId}/><button className="button" name="decision" value="approve">Approve after independent review / Duyệt sau rà soát độc lập</button><button className="button" name="decision" value="suspend">Suspend / Tạm dừng</button></form>}</section>
 <section className="panel"><h2>Verify legal representative / Xác minh đại diện pháp luật</h2><p>Store reference only. Identity/custody documents stay at school. A staff checkbox does not grant family consent. / Chỉ lưu tham chiếu; giấy tờ ở trường. Ô nhân viên không cấp đồng ý gia đình.</p><form action={verifyRepresentative}><input type="hidden" name="organizationId" value={organizationId}/><label>Learner profile ID / Mã hồ sơ học viên<input name="learnerId" required/></label><label>Representative profile ID / Mã đại diện<input name="representativeId" required/></label><label>School evidence reference / Tham chiếu minh chứng<input name="evidenceReference" required minLength={5} maxLength={250}/></label><label><input type="checkbox" name="verifiedAuthority" required/> Legal authority verified outside CCJ / Đã xác minh thẩm quyền bên ngoài.</label><label><input type="checkbox" name="verifiedAdult" required/> Adult identity verified / Đã xác minh người lớn.</label><button className="button">Record verification / Ghi xác minh</button></form>{authorities.map(a=><form key={String(a.id)} action={revokeRepresentative}><input type="hidden" name="organizationId" value={organizationId}/><input type="hidden" name="authorityId" value={String(a.id)}/><p>{String(a.learner_id)} → {String(a.representative_profile_id)} / {String(a.status)}</p><button className="button">Revoke / Thu hồi</button></form>)}</section>
 <section className="panel"><h2>Rights review queue / Hàng đợi quyền</h2>{rights.map(r=><form action={reviewPrivacyRightsRequest} key={String(r.id)}><input type="hidden" name="organizationId" value={organizationId}/><input type="hidden" name="requestId" value={String(r.id)}/><p>{String(r.request_type)} — {String(r.status)} — {String(r.created_at)}</p><label>Status / Trạng thái<select name="status"><option value="acknowledged">Acknowledged / Xác nhận</option><option value="in_review">In review / Rà soát</option><option value="completed">Executed / Đã thực hiện</option><option value="lawful_hold">Explained legal hold / Giữ theo luật có giải thích</option></select></label><label>Execution/hold evidence reference / Tham chiếu thực thi/giữ<input name="executionReference" maxLength={500}/></label><button className="button">Record review / Ghi rà soát</button></form>)}</section></div></main>;
}
